### ISSUE TITLE
Структурировать код в add_book.php

### ISSUE THREAD

**Issue by andrey-ilyin** [Angaev/AutoBook#6]
Надо переработать код и избавиться от большой вложенности if.

**Comment by Angaev** [comment]
Код стал более линейным 

    if (empty($_POST['book_name'])) {
        redirect('/new_book.php?result=2');
    }  
    $name = $_POST['book_name'];

    if (empty($_POST['year']) && is_numeric(($_POST['year']))) {
        redirect('/new_book.php?result=2');
    }
    $year = intval($_POST['year']);
            
    if (empty($_POST['publishing_house']) && is_numeric(($_POST['publishing_house']))) {
        redirect('/new_book.php?result=2');
    }      
    $houseId = $_POST['publishing_house'];
