### ISSUE TITLE
Переделать выборку книг в функции loadDataBooks без использования JOIN

### ISSUE THREAD

**Issue by andrey-ilyin** [Angaev/AutoBook#9]
То же самое касается функций getTop50Books и loadBooks

**Comment by Angaev** [comment]
(SELECT COUNT(DISTINCT id) FROM likes WHERE likes.book_id = book_id) AS like_count

**Comment by andrey-ilyin** [comment]
В функции getAllLikedBooks остался JOIN с таблицей likes. По-моему, лишний.
